### PR TITLE
Stand alone log it with strings v3

### PR DESCRIPTION
**Pull request by ben-farnham**
I'd like to merge this to the master branch of this stand-alone LogIt. It's required to unblock Wiener from starting work on their HAL.

I think originally this stand-alone LogIt repo was created for open62451-compat (also stand-alone) yes? Maybe if you could just give that a run to see if there are problems.

### CODE REVIEW

**Comment by pnikiel** [comment]
Seems to break the build with sth rather trivial:

$ cmake ../
fatal: destination path '/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/open62541-compat/LogIt' already exists and is not an empty directory.
CMake Error at LogIt/CMakeLists.txt:26 (message):
  environment variable BOOST_PATH_HEADERS not defined - please set this to a
  64bit boost installation include directory


-- Configuring incomplete, errors occurred!
See also "/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/open62541-compat/build/CMakeFiles/CMakeOutput.log".



could you maybe try yourself with open62541-compat?
Could you simply clone it, then run "build_standalone.py" which should arrange the basic stuff. Should build fine after the first go. Then checkout your new branch in LogIt directory, and get back to parent to fix building ... 

let me know if possible on your end

**Comment by pnikiel** [comment]
FYI I exported BOOST_PATH_HEADERS, then it complains about BOOST_HOME which I did, but it seems not to notice it:

$ export BOOST_HOME=/usr/lib64
[pnikiel@pcatldcsp11 build]$ make
fatal: destination path '/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/open62541-compat/LogIt' already exists and is not an empty directory.
CMake Error at LogIt/CMakeLists.txt:29 (message):
  environment variable BOOST_HOME not defined - please set this to a 64bit
  boost installation library directory


-- Configuring incomplete, errors occurred!
See also "/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/open62541-compat/build/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] Error 1

**Comment by ben-farnham** [comment]
OK, I'll give it a go from my end.

**Comment by pnikiel** [comment]
Hi Ben,
better, but still not right.
LogIt builds into something like this:

Linking CXX shared library libLogIt_lib.so

and the resulting standalone open62541-compat doesn't include it:

Linking CXX executable demo
CMakeFiles/demo.dir/demo.o: In function `main':
/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/demo.cpp:30: undefined reference to `Log::initializeLogging(Log::LOG_LEVEL const&)'
/home/pnikiel/gitProjects/ClientExtensionsForOpen62541Compat/open62541-compat/build/libopen62541-compat.a(uavariant.cpp.o): In function `UaVariant::UaVariant()':
uavariant.cpp:(.text+0x1a3): undefined reference to `Log::isLoggable(Log::LOG_LEVEL const&)'
uavariant.cpp:(.text+0x210): undefined reference to `LogRecord::LogRecord(std::string const&, int const&, Log::LOG_LEVEL const&)'
uavariant.cpp:(.text+0x21f): undefined reference to `LogRecord::getStream()'
uavariant.cpp:(.text+0x26b): undefined reference to `LogRecord::~LogRecord()'
uavariant.cpp:(.text+0x297): undefined reference to `LogRecord::~LogRecord()'

... etc ... the list is long ...

**Comment by ben-farnham** [comment]
My turn to be confused - think LogIt building OK, but the compat layer doesn't build, fails with the error below. How do I tell the compat layer where boost is?

image

**Comment by pnikiel** [comment]
Good point ... not supported yet, so far (for stand-alone builds) it would just use system's default which apparently you don't have.
The topic is being discussed here:
https://its.cern.ch/jira/browse/OPCUA-947

**Comment by ben-farnham** [comment]
Hi Piotr,

So, what to do for this LogIt branch at the moment? Doesn't need a resolution today but I would like this branch to be merged in the not too distant future (like next week) so Wiener can start building their HAL with one less complication (i.e. just using regular master).

I must say, as regards open62541-compat and boost.... In a different context, I spent about an hour this week trying to get cmake's find_package(Boost ...) working on windows. It _looks_ like a nice clean approach but I never once got it to actually discover boost: I ran out of time, gave up and reverted to importing the binary libraries 'long hand' in the CMakeLists.txt. So, not the most encouraging experience - maybe it works fine and I missed something.

Cheers,
Ben

**Comment by pnikiel** [comment]
Sorry,
didn't realize it is hanging on me.
I can have a look, probably on Monday though!

best piotr
________________________________

**Comment by ben-farnham** [comment]
Great, thanks.

**Pull request merged**
